[file:Season1.nml]
mode=auto
source=namelist:base_mesh
      =namelist:extrusion
      =namelist:finite_element
      =namelist:io
      =namelist:logging
      =namelist:planet
      =namelist:partitioning
      =namelist:time
      =namelist:timestepping
      =namelist:donkey(season1)
      =namelist:master(season1)
      =namelist:pleb(season1)
      =namelist:sith(season1)
      =namelist:weapon(season1)

[namelist:donkey(season1)]
age=34
capacity=2.75
fuel='snickers'
name='The Rush'
weight=6.0

[namelist:master(season1)]
age=23
height=3.4
name='bob'
own_series=.true.
street_cred=2

[namelist:pleb(season1)]
age=26
for_fodder=.false.
name='redshirt'
race='not turnips'

[namelist:sith(season1)]
age=26
height=3.4
name='bill'
own_series=.false.
street_cred=20

[namelist:weapon(season1)]
defensive=.false.
name='lemon'
onehanded=.true.
special_move='pancake pickle'
strike_damage=20
