[file:Season2.nml]
mode=auto
source=namelist:base_mesh
      =namelist:extrusion
      =namelist:finite_element
      =namelist:io
      =namelist:logging
      =namelist:planet
      =namelist:partitioning
      =namelist:time
      =namelist:timestepping
      =namelist:donkey(season2)
      =namelist:master(season2)
      =namelist:pleb(season2)
      =namelist:sith(season2)
      =namelist:weapon(season2)

[namelist:donkey(season2)]
age=26
capacity=20.3
fuel='turnips'
name='bill'
weight=4.5

[namelist:master(season2)]
age=27
height=2.4
name='Curly'
own_series=.true.
street_cred=1

[namelist:pleb(season2)]
age=26
for_fodder=.false.
name='redshirt'
race='not turnips'

[namelist:sith(season2)]
age=230
height=4.4
name='Beasty'
own_series=.true.
street_cred=15

[namelist:weapon(season2)]
defensive=.true.
name='bin'
onehanded=.false.
special_move='smash'
strike_damage=5
