import=lfric-driver/HEAD

[namelist:Master]
compulsory=true
description=
help=
ns=namelist/Jedi/Master
sort-key=
title=MasterDetails

[namelist:Master=name]
compulsory=true
type=character
!string_length=default


[namelist:Master=age]
compulsory=true
type=integer

[namelist:Master=height]
compulsory=true
!kind=default
type=real

[namelist:Master=street_cred]
compulsory=true
!kind=default
type=integer

[namelist:Master=OwnSeries]
compulsory=true
type=logical
!kind=default






[namelist:Sith]
compulsory=true
description=
help=
ns=namelist/Jedi/Sith
sort-key=
title=SithDetails

[namelist:Sith=name]
compulsory=true
type=character
!string_length=default

[namelist:Sith=age]
compulsory=true
!kind=default
type=integer

[namelist:Sith=height]
compulsory=true
!kind=default
type=real

[namelist:Sith=street_cred]
compulsory=true
!kind=default
type=integer

[namelist:Sith=OwnSeries]
compulsory=true
type=logical
!kind=default


[namelist:Donkey]
compulsory=true
description=
help=
ns=namelist/Jedi/Donkey
sort-key=
title=JediTransporter

[namelist:Donkey=name]
compulsory=true
type=character
!string_length=default

[namelist:Donkey=age]
compulsory=true
type=integer
!kind=default

[namelist:Donkey=fuel]
compulsory=true
type=character
!string_length=default

[namelist:Donkey=weight]
compulsory=true
!kind=default
type=real

[namelist:Donkey=capacity]
compulsory=true
!kind=default
type=real

[namelist:Pleb]
compulsory=true
description=
help=
ns=namelist/Jedi/Pleb
sort-key=
title=JediWannabe

[namelist:Pleb=name]
compulsory=true
type=character
!string_length=default

[namelist:Pleb=age]
compulsory=true
!kind=default
type=integer

[namelist:Pleb=race]
compulsory=true
type=character
!string_length=default

[namelist:Pleb=for_fodder]
compulsory=true
type=logical
!kind=default

[namelist:Weapon]
compulsory=true
description=
help=
ns=namelist/Jedi/Weapon
sort-key=
title=JediToys

[namelist:Weapon=name]
compulsory=true
type=character
!string_length=default

[namelist:Weapon=onehanded]
compulsory=true
!kind=default
type=logical

[namelist:Weapon=defensive]
compulsory=true
!kind=default
type=logical

[namelist:Weapon=strike_damage]
compulsory=true
type=integer
!kind=default

[namelist:Weapon=special_move]
compulsory=true
type=character
!string_length=default
