import=lfric-driver/HEAD

[namelist:master]
compulsory=true
description=
help=
ns=namelist/Jedi/Master
sort-key=
title=MasterDetails

[namelist:master=name]
compulsory=true
type=character
!string_length=default


[namelist:master=age]
compulsory=true
type=integer

[namelist:master=height]
compulsory=true
!kind=default
type=real

[namelist:master=street_cred]
compulsory=true
!kind=default
type=integer

[namelist:master=OwnSeries]
compulsory=true
type=logical
!kind=default






[namelist:sith]
compulsory=true
description=
help=
ns=namelist/Jedi/Sith
sort-key=
title=SithDetails

[namelist:sith=name]
compulsory=true
type=character
!string_length=default

[namelist:sith=age]
compulsory=true
!kind=default
type=integer

[namelist:sith=height]
compulsory=true
!kind=default
type=real

[namelist:sith=street_cred]
compulsory=true
!kind=default
type=integer

[namelist:sith=OwnSeries]
compulsory=true
type=logical
!kind=default


[namelist:donkey]
compulsory=true
description=
help=
ns=namelist/Jedi/Donkey
sort-key=
title=JediTransporter

[namelist:donkey=name]
compulsory=true
type=character
!string_length=default

[namelist:donkey=age]
compulsory=true
type=integer
!kind=default

[namelist:donkey=fuel]
compulsory=true
type=character
!string_length=default

[namelist:donkey=weight]
compulsory=true
!kind=default
type=real

[namelist:donkey=capacity]
compulsory=true
!kind=default
type=real

[namelist:pleb]
compulsory=true
description=
help=
ns=namelist/Jedi/Pleb
sort-key=
title=JediWannabe

[namelist:pleb=name]
compulsory=true
type=character
!string_length=default

[namelist:pleb=age]
compulsory=true
!kind=default
type=integer

[namelist:pleb=race]
compulsory=true
type=character
!string_length=default

[namelist:pleb=for_fodder]
compulsory=true
type=logical
!kind=default

[namelist:weapon]
compulsory=true
description=
help=
ns=namelist/Jedi/Weapon
sort-key=
title=JediToys

[namelist:weapon=name]
compulsory=true
type=character
!string_length=default

[namelist:weapon=onehanded]
compulsory=true
!kind=default
type=logical

[namelist:weapon=defensive]
compulsory=true
!kind=default
type=logical

[namelist:weapon=strike_damage]
compulsory=true
type=integer
!kind=default

[namelist:weapon=special_move]
compulsory=true
type=character
!string_length=default
