import=lfric-driver/HEAD

[namelist:donkey]
description=
duplicate=true
help=
ns=namelist/Jedi/Donkey
sort-key=
title=JediTransporter

[namelist:donkey=age]
compulsory=true
!kind=default
type=integer

[namelist:donkey=capacity]
compulsory=true
!kind=default
type=real

[namelist:donkey=fuel]
compulsory=true
!string_length=default
type=character

[namelist:donkey=name]
compulsory=true
!string_length=default
type=character

[namelist:donkey=weight]
compulsory=true
!kind=default
type=real

[namelist:master]
description=
duplicate=true
help=
ns=namelist/Jedi/Master
sort-key=
title=MasterDetails

[namelist:master=age]
compulsory=true
type=integer

[namelist:master=height]
compulsory=true
!kind=default
type=real

[namelist:master=name]
compulsory=true
!string_length=default
type=character

[namelist:master=own_series]
compulsory=true
!kind=default
type=logical

[namelist:master=street_cred]
compulsory=true
!kind=default
type=integer

[namelist:pleb]
description=
duplicate=true
help=
ns=namelist/Jedi/Pleb
sort-key=
title=JediWannabe

[namelist:pleb=age]
compulsory=true
!kind=default
type=integer

[namelist:pleb=for_fodder]
compulsory=true
!kind=default
type=logical

[namelist:pleb=name]
compulsory=true
!string_length=default
type=character

[namelist:pleb=race]
compulsory=true
!string_length=default
type=character

[namelist:sith]
description=
duplicate=true
help=
ns=namelist/Jedi/Sith
sort-key=
title=SithDetails

[namelist:sith=age]
compulsory=true
!kind=default
type=integer

[namelist:sith=height]
compulsory=true
!kind=default
type=real

[namelist:sith=name]
compulsory=true
!string_length=default
type=character

[namelist:sith=own_series]
compulsory=true
!kind=default
type=logical

[namelist:sith=street_cred]
compulsory=true
!kind=default
type=integer

[namelist:weapon]
description=
duplicate=true
help=
ns=namelist/Jedi/Weapon
sort-key=
title=JediToys

[namelist:weapon=defensive]
compulsory=true
!kind=default
type=logical

[namelist:weapon=name]
compulsory=true
!string_length=default
type=character

[namelist:weapon=onehanded]
compulsory=true
!kind=default
type=logical

[namelist:weapon=special_move]
compulsory=true
!string_length=default
type=character

[namelist:weapon=strike_damage]
compulsory=true
!kind=default
type=integer
